[package]
name = "soul-media"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.104"
hex = "0.4.3"
image = "0.25.10"
infer = "0.22.0"
resvg = "0.48.1"
serde = "1.0.229"
serde_json = "1.0.151"
sha2 = "0.11.0"
soul-core = { version = "0.1.0", path = "../soul-core" }
tempfile = "3.27.0"
thiserror = "2.0.20"
tiny-skia = "0.12.0"
usvg = "0.48.1"
